# Generated by Django 4.1.2 on 2022-11-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
    ]
